// Exercise categories
export const EXERCISE_CATEGORIES = {
  chest: 'Chest',
  back: 'Back',
  shoulders: 'Shoulders',
  arms: 'Arms',
  legs: 'Legs',
  core: 'Core',
  cardio: 'Cardio',
  compound: 'Compound',
};

export const EXERCISES = [
  // Chest
  { id: 'bench_press', name: 'Bench Press', intensity: 1.2, category: 'chest' },
  { id: 'incline_bench', name: 'Incline Bench Press', intensity: 1.2, category: 'chest' },
  { id: 'decline_bench', name: 'Decline Bench Press', intensity: 1.2, category: 'chest' },
  { id: 'dumbbell_press', name: 'Dumbbell Press', intensity: 1.1, category: 'chest' },
  { id: 'incline_dumbbell', name: 'Incline Dumbbell Press', intensity: 1.1, category: 'chest' },
  { id: 'chest_fly', name: 'Chest Fly', intensity: 0.8, category: 'chest' },
  { id: 'cable_crossover', name: 'Cable Crossover', intensity: 0.8, category: 'chest' },
  { id: 'pushups', name: 'Pushups', intensity: 0.5, category: 'chest' },
  { id: 'dips', name: 'Dips', intensity: 1.0, category: 'chest' },
  { id: 'pec_deck', name: 'Pec Deck', intensity: 0.7, category: 'chest' },

  // Back
  { id: 'pullups', name: 'Pull-ups', intensity: 1.0, category: 'back' },
  { id: 'chin_ups', name: 'Chin-ups', intensity: 1.0, category: 'back' },
  { id: 'lat_pulldown', name: 'Lat Pulldown', intensity: 0.9, category: 'back' },
  { id: 'barbell_row', name: 'Barbell Row', intensity: 1.2, category: 'back' },
  { id: 'dumbbell_row', name: 'Dumbbell Row', intensity: 1.0, category: 'back' },
  { id: 'cable_row', name: 'Cable Row', intensity: 0.9, category: 'back' },
  { id: 'seated_row', name: 'Seated Row', intensity: 0.9, category: 'back' },
  { id: 't_bar_row', name: 'T-Bar Row', intensity: 1.1, category: 'back' },
  { id: 'face_pulls', name: 'Face Pulls', intensity: 0.6, category: 'back' },
  { id: 'shrugs', name: 'Shrugs', intensity: 0.7, category: 'back' },

  // Shoulders
  { id: 'overhead_press', name: 'Overhead Press', intensity: 1.2, category: 'shoulders' },
  { id: 'military_press', name: 'Military Press', intensity: 1.2, category: 'shoulders' },
  { id: 'dumbbell_shoulder', name: 'Dumbbell Shoulder Press', intensity: 1.1, category: 'shoulders' },
  { id: 'arnold_press', name: 'Arnold Press', intensity: 1.0, category: 'shoulders' },
  { id: 'lateral_raise', name: 'Lateral Raise', intensity: 0.6, category: 'shoulders' },
  { id: 'front_raise', name: 'Front Raise', intensity: 0.6, category: 'shoulders' },
  { id: 'rear_delt_fly', name: 'Rear Delt Fly', intensity: 0.6, category: 'shoulders' },
  { id: 'upright_row', name: 'Upright Row', intensity: 0.8, category: 'shoulders' },

  // Arms
  { id: 'barbell_curl', name: 'Barbell Curl', intensity: 0.7, category: 'arms' },
  { id: 'dumbbell_curl', name: 'Dumbbell Curl', intensity: 0.6, category: 'arms' },
  { id: 'hammer_curl', name: 'Hammer Curl', intensity: 0.6, category: 'arms' },
  { id: 'preacher_curl', name: 'Preacher Curl', intensity: 0.7, category: 'arms' },
  { id: 'concentration_curl', name: 'Concentration Curl', intensity: 0.6, category: 'arms' },
  { id: 'cable_curl', name: 'Cable Curl', intensity: 0.6, category: 'arms' },
  { id: 'tricep_pushdown', name: 'Tricep Pushdown', intensity: 0.6, category: 'arms' },
  { id: 'skull_crushers', name: 'Skull Crushers', intensity: 0.8, category: 'arms' },
  { id: 'tricep_extension', name: 'Tricep Extension', intensity: 0.7, category: 'arms' },
  { id: 'close_grip_bench', name: 'Close Grip Bench Press', intensity: 1.0, category: 'arms' },
  { id: 'diamond_pushups', name: 'Diamond Pushups', intensity: 0.6, category: 'arms' },

  // Legs
  { id: 'squat', name: 'Squat', intensity: 1.5, category: 'legs' },
  { id: 'front_squat', name: 'Front Squat', intensity: 1.4, category: 'legs' },
  { id: 'hack_squat', name: 'Hack Squat', intensity: 1.3, category: 'legs' },
  { id: 'leg_press', name: 'Leg Press', intensity: 1.2, category: 'legs' },
  { id: 'lunges', name: 'Lunges', intensity: 0.8, category: 'legs' },
  { id: 'walking_lunges', name: 'Walking Lunges', intensity: 0.9, category: 'legs' },
  { id: 'bulgarian_split', name: 'Bulgarian Split Squat', intensity: 1.0, category: 'legs' },
  { id: 'leg_extension', name: 'Leg Extension', intensity: 0.7, category: 'legs' },
  { id: 'leg_curl', name: 'Leg Curl', intensity: 0.7, category: 'legs' },
  { id: 'romanian_deadlift', name: 'Romanian Deadlift', intensity: 1.3, category: 'legs' },
  { id: 'stiff_leg_deadlift', name: 'Stiff Leg Deadlift', intensity: 1.2, category: 'legs' },
  { id: 'calf_raise', name: 'Calf Raise', intensity: 0.5, category: 'legs' },
  { id: 'seated_calf_raise', name: 'Seated Calf Raise', intensity: 0.5, category: 'legs' },
  { id: 'hip_thrust', name: 'Hip Thrust', intensity: 1.0, category: 'legs' },
  { id: 'glute_bridge', name: 'Glute Bridge', intensity: 0.7, category: 'legs' },
  { id: 'goblet_squat', name: 'Goblet Squat', intensity: 0.9, category: 'legs' },
  { id: 'step_ups', name: 'Step Ups', intensity: 0.8, category: 'legs' },
  { id: 'sumo_squat', name: 'Sumo Squat', intensity: 1.2, category: 'legs' },
  { id: 'sissy_squat', name: 'Sissy Squat', intensity: 0.8, category: 'legs' },
  { id: 'adductor', name: 'Adductor Machine', intensity: 0.6, category: 'legs' },
  { id: 'abductor', name: 'Abductor Machine', intensity: 0.6, category: 'legs' },

  // Core
  { id: 'situps', name: 'Sit-ups', intensity: 0.4, category: 'core' },
  { id: 'crunches', name: 'Crunches', intensity: 0.3, category: 'core' },
  { id: 'plank', name: 'Plank (seconds)', intensity: 0.1, category: 'core' },
  { id: 'side_plank', name: 'Side Plank (seconds)', intensity: 0.1, category: 'core' },
  { id: 'leg_raises', name: 'Leg Raises', intensity: 0.5, category: 'core' },
  { id: 'hanging_leg_raise', name: 'Hanging Leg Raise', intensity: 0.7, category: 'core' },
  { id: 'russian_twist', name: 'Russian Twist', intensity: 0.4, category: 'core' },
  { id: 'cable_crunch', name: 'Cable Crunch', intensity: 0.5, category: 'core' },
  { id: 'ab_wheel', name: 'Ab Wheel Rollout', intensity: 0.7, category: 'core' },
  { id: 'mountain_climbers', name: 'Mountain Climbers', intensity: 0.6, category: 'core' },
  { id: 'dead_bug', name: 'Dead Bug', intensity: 0.4, category: 'core' },
  { id: 'bicycle_crunch', name: 'Bicycle Crunch', intensity: 0.5, category: 'core' },

  // Compound
  { id: 'deadlift', name: 'Deadlift', intensity: 1.8, category: 'compound' },
  { id: 'sumo_deadlift', name: 'Sumo Deadlift', intensity: 1.7, category: 'compound' },
  { id: 'clean_and_press', name: 'Clean and Press', intensity: 1.5, category: 'compound' },
  { id: 'power_clean', name: 'Power Clean', intensity: 1.4, category: 'compound' },
  { id: 'snatch', name: 'Snatch', intensity: 1.5, category: 'compound' },
  { id: 'thruster', name: 'Thruster', intensity: 1.3, category: 'compound' },
  { id: 'burpees', name: 'Burpees', intensity: 1.5, category: 'compound' },
  { id: 'kettlebell_swing', name: 'Kettlebell Swing', intensity: 1.0, category: 'compound' },
  { id: 'farmers_walk', name: 'Farmers Walk', intensity: 0.9, category: 'compound' },

  // Cardio
  { id: 'run', name: 'Run (Km)', intensity: 10.0, category: 'cardio' },
  { id: 'treadmill', name: 'Treadmill (mins)', intensity: 0.3, category: 'cardio' },
  { id: 'cycling', name: 'Cycling (mins)', intensity: 0.25, category: 'cardio' },
  { id: 'rowing', name: 'Rowing (mins)', intensity: 0.35, category: 'cardio' },
  { id: 'stair_climber', name: 'Stair Climber (mins)', intensity: 0.4, category: 'cardio' },
  { id: 'jump_rope', name: 'Jump Rope (mins)', intensity: 0.5, category: 'cardio' },
  { id: 'elliptical', name: 'Elliptical (mins)', intensity: 0.25, category: 'cardio' },
  { id: 'swimming', name: 'Swimming (mins)', intensity: 0.4, category: 'cardio' },
  { id: 'box_jumps', name: 'Box Jumps', intensity: 0.8, category: 'cardio' },
  { id: 'battle_ropes', name: 'Battle Ropes (mins)', intensity: 0.5, category: 'cardio' },
];
